#!/bin/bash
# ==============================================================================
# DPG Deployment - Configuration Generation
# ==============================================================================
# Functions for generating Terraform configuration files.
# ==============================================================================

# ==============================================================================
# Generate Configuration
# ==============================================================================

generate_config() {
    local provider="$1"
    local template="$2"
    
    log "STEP" "Generating configuration..."
    
    if [[ -z "$ENV_DIR" ]]; then
        log "ERROR" "Environment directory not set"
        return 1
    fi
    
    local template_file="${ENV_DIR}/terraform.tfvars.example"
    if [[ -f "$template_file" ]]; then
        cp "$template_file" "$CONFIG_FILE"
    fi
    
    cat > "$CONFIG_FILE" << EOF
# ==============================================================================
# DPG Infrastructure Configuration
# Generated by deploy.sh on $(date)
# Provider: $provider | Environment: $ENVIRONMENT | Template: $template
# ==============================================================================

# General Configuration
project_name = "${PROJECT_NAME:-dpg-infra}"
environment  = "${ENVIRONMENT:-staging}"
owner        = "${OWNER:-DPG Deployment}"

EOF

    case "$provider" in
        aws)
            _generate_aws_config
            ;;
        azure)
            _generate_azure_config
            ;;
        gcp)
            _generate_gcp_config
            ;;
    esac
    
    # Add template-specific settings
    _generate_template_config "$template"
    
    log "SUCCESS" "Configuration saved to: $CONFIG_FILE"
}

# ==============================================================================
# Provider-Specific Configuration Generators
# ==============================================================================

_generate_aws_config() {
    cat >> "$CONFIG_FILE" << EOF
# AWS Configuration
aws_region         = "${REGION:-ap-south-1}"
availability_zones = ["${REGION:-ap-south-1}a", "${REGION:-ap-south-1}b"]
instance_type      = "${INSTANCE_TYPE:-g4dn.xlarge}"
root_volume_size   = ${VOLUME_SIZE:-100}
EOF
}

_generate_azure_config() {
    cat >> "$CONFIG_FILE" << EOF
# Azure Configuration
azure_location        = "${REGION:-centralindia}"
azure_subscription_id = "${AZURE_SUBSCRIPTION_ID:-}"
vm_size               = "${INSTANCE_TYPE:-Standard_NC4as_T4_v3}"
root_volume_size      = ${VOLUME_SIZE:-100}
EOF
}

_generate_gcp_config() {
    cat >> "$CONFIG_FILE" << EOF
# GCP Configuration
gcp_project_id   = "${GCP_PROJECT_ID:-}"
gcp_region       = "${REGION:-asia-south1}"
gcp_zone         = "${REGION:-asia-south1}-a"
machine_type     = "${MACHINE_TYPE:-n1-standard-4}"
gpu_type         = "${GPU_TYPE:-nvidia-tesla-t4}"
gpu_count        = ${GPU_COUNT:-1}
root_volume_size = ${VOLUME_SIZE:-100}
EOF
}

# ==============================================================================
# Template-Specific Configuration
# ==============================================================================

_generate_template_config() {
    local template="$1"
    
    case "$template" in
        minimal|development)
            cat >> "$CONFIG_FILE" << EOF

# Minimal/Development Settings
asg_min_size         = 1
asg_max_size         = 1
asg_desired_capacity = 1
enable_load_balancer = false
enable_scheduling    = false
EOF
            ;;
        standard)
            cat >> "$CONFIG_FILE" << EOF

# Standard Settings
asg_min_size         = 1
asg_max_size         = 3
asg_desired_capacity = 1
enable_load_balancer = true
enable_scheduling    = true
EOF
            ;;
        production)
            cat >> "$CONFIG_FILE" << EOF

# Production Settings
asg_min_size         = 2
asg_max_size         = 10
asg_desired_capacity = 2
enable_load_balancer = true
enable_scheduling    = true
EOF
            ;;
    esac
}
