#!/bin/bash
# ==============================================================================
# Initialization - Terraform Configuration
# ==============================================================================
# Generates terraform.tfvars and runs terraform init/plan.
# ==============================================================================

# ==============================================================================
# Terraform Variables Generation
# ==============================================================================

generate_tfvars() {
    echo -e "\n${BLUE}Step 5: Generating terraform.tfvars${NC}"
    
    local TFVARS_FILE="$PROJECT_ROOT/terraform.tfvars"
    
    cat > "$TFVARS_FILE" << EOF
# Auto-generated by init.sh on $(date)
# Cloud Provider Configuration
cloud_provider = "$CLOUD_PROVIDER"

# Project Configuration
project_name   = "gpu-infra"
environment    = "dev"
instance_count = 1

# GPU Configuration
install_nvidia_driver = true
nvidia_driver_version = "535"

# Scheduling (optional)
enable_scheduling = false
EOF

    # Add provider-specific configuration
    case $CLOUD_PROVIDER in
        aws)
            cat >> "$TFVARS_FILE" << EOF

# AWS Configuration
aws_region = "${AWS_REGION:-ap-south-1}"
EOF
            ;;
        azure)
            cat >> "$TFVARS_FILE" << EOF

# Azure Configuration
azure_subscription_id = "$AZURE_SUBSCRIPTION_ID"
azure_client_id       = "$AZURE_CLIENT_ID"
azure_client_secret   = "$AZURE_CLIENT_SECRET"
azure_tenant_id       = "$AZURE_TENANT_ID"
azure_location        = "${AZURE_LOCATION:-centralindia}"
EOF
            ;;
        gcp)
            cat >> "$TFVARS_FILE" << EOF

# GCP Configuration
gcp_project        = "$GCP_PROJECT_ID"
gcp_region         = "${GCP_REGION:-asia-south1}"
gcp_credentials    = "$GCP_CREDENTIALS_FILE"
EOF
            ;;
    esac

    echo -e "${GREEN}✓ terraform.tfvars generated${NC}"
    echo ""
    cat "$TFVARS_FILE"
    echo ""
}

# ==============================================================================
# Terraform Initialization
# ==============================================================================

run_terraform_init() {
    echo -e "\n${BLUE}Step 6: Initializing Terraform${NC}"
    
    cd "$PROJECT_ROOT"
    terraform init
    
    if [ $? -ne 0 ]; then
        echo -e "${RED}Terraform init failed!${NC}"
        exit 1
    fi
    
    echo -e "${GREEN}✓ Terraform initialized successfully${NC}"
}

# ==============================================================================
# Terraform Plan
# ==============================================================================

run_terraform_plan() {
    echo -e "\n${BLUE}Step 7: Creating execution plan${NC}"
    
    terraform plan -out=tfplan
    
    if [ $? -ne 0 ]; then
        echo -e "${RED}Terraform plan failed!${NC}"
        exit 1
    fi
    
    echo -e "${GREEN}✓ Plan created successfully${NC}"
}

# ==============================================================================
# Display Next Steps
# ==============================================================================

show_next_steps() {
    echo -e "\n${GREEN}════════════════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}                    Initialization Complete!${NC}"
    echo -e "${GREEN}════════════════════════════════════════════════════════════════${NC}"
    echo ""
    echo "Your GPU infrastructure is ready to deploy."
    echo ""
    echo -e "${YELLOW}Next steps:${NC}"
    echo "  1. Review the plan above"
    echo "  2. Apply the configuration:"
    echo "     terraform apply tfplan"
    echo ""
    echo -e "${YELLOW}Or use the deployment script:${NC}"
    echo "     ./deploy.sh deploy"
    echo ""
    echo -e "${YELLOW}Useful commands:${NC}"
    echo "     terraform show         # Show current state"
    echo "     terraform output       # Show outputs"
    echo "     terraform destroy      # Destroy infrastructure"
    echo ""
}

# ==============================================================================
# Execute Terraform Steps
# ==============================================================================

execute_terraform_setup() {
    generate_tfvars
    run_terraform_init
    run_terraform_plan
    show_next_steps
}
